### PR TITLE
fix: improve relative link generation

### LINKED ISSUE #21: Review relative navigation
`path` may contain params like so: 'route/:param'. 
So, in order to do relative navigation you should use `history.push(`${match.url}/format`);`
Please check this

### PR DESCRIPTION
**Pull request by sashaqred**
Closes #21

### CODE REVIEW

File: src/@modules/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx [hunk 1]
```diff
@@ -6,16 +6,16 @@ import { setDependencies } from '../../actions';
 import { DependencyRedactor } from '../DependencyRedactor';
 
 export function DependencyFormatter() {
-  const { path } = useRouteMatch();
+  const { path, url } = useRouteMatch();
```
Comment (Roma36) [inline src/@modules/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx:9]: path is not used anymore

**Review by Roma36 — CHANGES_REQUESTED** [review]

File: src/@modules/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx (hunk 1 above)
Comment (sashaqred) [reply src/@modules/DependencyFormatter/containers/DependencyFormatter/DependencyFormatter.tsx:9]: For now, url is used for link generation. Path for routes generation.
Just link in that [example](https://reacttraining.com/react-router/web/example/nesting)

**Review by Roma36 — APPROVED** [review]
